# Generated by Django 5.2.5 on 2025-11-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('savings', 'Saving')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('complete', 'Completed'), ('pending', 'Pending')], default='complete', max_length=20)),
            ],
        ),
    ]
